{% set python_min = python_min|default("0.1a0") %}
{% set name = "schedulefree" %}
{% set version = "1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/schedulefree-{{ version }}.tar.gz
  sha256: 59b7ec9ac0f714730cbcdde435b7d9b415d3fc3c5d2133e0f124e07aba4ba86a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}.*
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - pytorch >=2.0
    - typing_extensions

test:
  imports:
    - schedulefree
  commands:
    - pip check
  requires:
    - python ={{ python_min }}
    - pip

about:
  home: https://github.com/facebookresearch/schedule_free
  summary: Schedule Free Learning in PyTorch
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - synapticarbors
