{% set name = "schedulefree" %}
{% set version = "1.2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/schedulefree-{{ version }}.tar.gz
  sha256: e97f8b8db332dafc9999a2c4ed68429606579d5eb250ebb953f233efffdc79c1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.4
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >=3.4
    - pytorch >=2.0
    - typing_extensions

test:
  imports:
    - schedulefree
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/facebookresearch/schedule_free
  summary: Schedule Free Learning in PyTorch
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - synapticarbors
