context:
  version: 1.4.1
  python_min: '3.9'

package:
  name: schedulefree
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/schedulefree/schedulefree-${{ version }}.tar.gz
  sha256: 69ef25601d1fc0d8dd00cb36f9af78833f88b7846f1bb6ddecc9f144f3e9f7cb

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >=${{ python_min }}
    - pytorch
    - typing_extensions
tests:
  - python:
      imports:
        - schedulefree
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Schedule Free Learning in PyTorch
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/facebookresearch/schedule_free

extra:
  recipe-maintainers:
    - synapticarbors
